/*
	
  Copyright © 2025 Maximilian Jung

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation
  files (the “Software”), to deal in the Software without
  restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, sublicense, and/or
  sell copies of the Software, and to permit persons to whom the
  Software is furnished to do so, subject to the following
  conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the
  Software.

  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY
  KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
  PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
  OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
	
*/


#ifndef _KEYBOARD_H_
#define _KEYBOARD_H_


// Enumeration of IBM AT keyboard scan codes.
typedef enum {
    ScanCodeEsc          = 0x01,
    ScanCode1            = 0x02,
    ScanCode2            = 0x03,
    ScanCode3            = 0x04,
    ScanCode4            = 0x05,
    ScanCode5            = 0x06,
    ScanCode6            = 0x07,
    ScanCode7            = 0x08,
    ScanCode8            = 0x09,
    ScanCode9            = 0x0A,
    ScanCode0            = 0x0B,
    ScanCodeMinus        = 0x0C,
    ScanCodeEquals       = 0x0D,
    ScanCodeBackspace    = 0x0E,
    ScanCodeTab          = 0x0F,
    ScanCodeQ            = 0x10,
    ScanCodeW            = 0x11,
    ScanCodeE            = 0x12,
    ScanCodeR            = 0x13,
    ScanCodeT            = 0x14,
    ScanCodeY            = 0x15,
    ScanCodeU            = 0x16,
    ScanCodeI            = 0x17,
    ScanCodeO            = 0x18,
    ScanCodeP            = 0x19,
    ScanCodeLBracket     = 0x1A,
    ScanCodeRBracket     = 0x1B,
    ScanCodeEnter        = 0x1C,
    ScanCodeLCtrl        = 0x1D,
    ScanCodeA            = 0x1E,
    ScanCodeS            = 0x1F,
    ScanCodeD            = 0x20,
    ScanCodeF            = 0x21,
    ScanCodeG            = 0x22,
    ScanCodeH            = 0x23,
    ScanCodeJ            = 0x24,
    ScanCodeK            = 0x25,
    ScanCodeL            = 0x26,
    ScanCodeSemicolon    = 0x27,
    ScanCodeApostrophe   = 0x28,
    ScanCodeGrave        = 0x29,
    ScanCodeLShift       = 0x2A,
    ScanCodeBackslash    = 0x2B,
    ScanCodeZ            = 0x2C,
    ScanCodeX            = 0x2D,
    ScanCodeC            = 0x2E,
    ScanCodeV            = 0x2F,
    ScanCodeB            = 0x30,
    ScanCodeN            = 0x31,
    ScanCodeM            = 0x32,
    ScanCodeComma        = 0x33,
    ScanCodePeriod       = 0x34,
    ScanCodeSlash        = 0x35,
    ScanCodeRShift       = 0x36,
    ScanCodeKpAsterisk   = 0x37,
    ScanCodeLAlt         = 0x38,
    ScanCodeSpace        = 0x39,
    ScanCodeCapsLock     = 0x3A,
    ScanCodeF1           = 0x3B,
    ScanCodeF2           = 0x3C,
    ScanCodeF3           = 0x3D,
    ScanCodeF4           = 0x3E,
    ScanCodeF5           = 0x3F,
    ScanCodeF6           = 0x40,
    ScanCodeF7           = 0x41,
    ScanCodeF8           = 0x42,
    ScanCodeF9           = 0x43,
    ScanCodeF10          = 0x44,
    ScanCodeNumLock      = 0x45,
    ScanCodeScrollLock   = 0x46,
    ScanCodeKp7          = 0x47,
    ScanCodeKp8          = 0x48,
    ScanCodeKp9          = 0x49,
    ScanCodeKpMinus      = 0x4A,
    ScanCodeKp4          = 0x4B,
    ScanCodeKp5          = 0x4C,
    ScanCodeKp6          = 0x4D,
    ScanCodeKpPlus       = 0x4E,
    ScanCodeKp1          = 0x4F,
    ScanCodeKp2          = 0x50,
    ScanCodeKp3          = 0x51,
    ScanCodeKp0          = 0x52,
    ScanCodeKpPeriod     = 0x53,
    ScanCodeF11          = 0x57,
    ScanCodeF12          = 0x58,

    // Extended scancodes
    ScanCodeRCtrl        = 0xE01D,
    ScanCodeRAlt         = 0xE038,
    ScanCodeHome         = 0xE047,
    ScanCodeUp           = 0xE048,
    ScanCodePageUp       = 0xE049,
    ScanCodeLeft         = 0xE04B,
    ScanCodeRight        = 0xE04D,
    ScanCodeEnd          = 0xE04F,
    ScanCodeDown         = 0xE050,
    ScanCodePageDown     = 0xE051,
    ScanCodeInsert       = 0xE052,
    ScanCodeDelete       = 0xE053
} ScanCode;



// Abstract key codes
typedef enum {
    KeyCodeNone          = 0x00,
    KeyCodeError         = 0x01,
    KeyCodeReserved      = 0x02,
    KeyCodeSystem        = 0x03,
    KeyCodeA             = 0x04,
    KeyCodeB             = 0x05,
    KeyCodeC             = 0x06,
    KeyCodeD             = 0x07,
    KeyCodeE             = 0x08,
    KeyCodeF             = 0x09,
    KeyCodeG             = 0x0A,
    KeyCodeH             = 0x0B,
    KeyCodeI             = 0x0C,
    KeyCodeJ             = 0x0D,
    KeyCodeK             = 0x0E,
    KeyCodeL             = 0x0F,
    KeyCodeM             = 0x10,
    KeyCodeN             = 0x11,
    KeyCodeO             = 0x12,
    KeyCodeP             = 0x13,
    KeyCodeQ             = 0x14,
    KeyCodeR             = 0x15,
    KeyCodeS             = 0x16,
    KeyCodeT             = 0x17,
    KeyCodeU             = 0x18,
    KeyCodeV             = 0x19,
    KeyCodeW             = 0x1A,
    KeyCodeX             = 0x1B,
    KeyCodeY             = 0x1C,
    KeyCodeZ             = 0x1D,
    KeyCode1             = 0x1E,
    KeyCode2             = 0x1F,
    KeyCode3             = 0x20,
    KeyCode4             = 0x21,
    KeyCode5             = 0x22,
    KeyCode6             = 0x23,
    KeyCode7             = 0x24,
    KeyCode8             = 0x25,
    KeyCode9             = 0x26,
    KeyCode0             = 0x27,
    KeyCodeEnter         = 0x28,
    KeyCodeEsc           = 0x29,
    KeyCodeBackspace     = 0x2A,
    KeyCodeTab           = 0x2B,
    KeyCodeSpace         = 0x2C,
    KeyCodeMinus         = 0x2D,
    KeyCodeEquals        = 0x2E,
    KeyCodeLBracket      = 0x2F,
    KeyCodeRBracket      = 0x30,
    KeyCodeBackslash     = 0x31,
    KeyCodeSemicolon     = 0x32,
    KeyCodeApostrophe    = 0x33,
    KeyCodeGrave         = 0x34,
    KeyCodeComma         = 0x35,
    KeyCodePeriod        = 0x36,
    KeyCodeSlash         = 0x37,
    KeyCodeCapsLock      = 0x38,
    KeyCodeF1            = 0x39,
    KeyCodeF2            = 0x3A,
    KeyCodeF3            = 0x3B,
    KeyCodeF4            = 0x3C,
    KeyCodeF5            = 0x3D,
    KeyCodeF6            = 0x3E,
    KeyCodeF7            = 0x3F,
    KeyCodeF8            = 0x40,
    KeyCodeF9            = 0x41,
    KeyCodeF10           = 0x42,
    KeyCodeF11           = 0x43,
    KeyCodeF12           = 0x44,
    KeyCodePrintScreen   = 0x45,
    KeyCodeScrollLock    = 0x46,
    KeyCodePause         = 0x47,
    KeyCodeInsert        = 0x48,
    KeyCodeHome          = 0x49,
    KeyCodePageUp        = 0x4A,
    KeyCodeDelete        = 0x4B,
    KeyCodeEnd           = 0x4C,
    KeyCodePageDown      = 0x4D,
    KeyCodeRight         = 0x4E,
    KeyCodeLeft          = 0x4F,
    KeyCodeDown          = 0x50,
    KeyCodeUp            = 0x51,
    KeyCodeNumLock       = 0x52,
    KeyCodeKpSlash       = 0x53,
    KeyCodeKpAsterisk    = 0x54,
    KeyCodeKpMinus       = 0x55,
    KeyCodeKpPlus        = 0x56,
    KeyCodeKpEnter       = 0x57,
    KeyCodeKp1           = 0x58,
    KeyCodeKp2           = 0x59,
    KeyCodeKp3           = 0x5A,
    KeyCodeKp4           = 0x5B,
    KeyCodeKp5           = 0x5C,
    KeyCodeKp6           = 0x5D,
    KeyCodeKp7           = 0x5E,
    KeyCodeKp8           = 0x5F,
    KeyCodeKp9           = 0x60,
    KeyCodeKp0           = 0x61,
    KeyCodeKpPeriod      = 0x62,
    KeyCodeLCtrl         = 0x63,
    KeyCodeLShift        = 0x64,
    KeyCodeLAlt          = 0x65,
    KeyCodeLGui          = 0x66,
    KeyCodeRCtrl         = 0x67,
    KeyCodeRShift        = 0x68,
    KeyCodeRAlt          = 0x69,
    KeyCodeRGui          = 0x6A
} KeyCode;


static const KeyCode GermanKeyMap[0xff] = {
    [ScanCodeEsc]        = KeyCodeEsc,
    [ScanCode1]          = KeyCode1,
    [ScanCode2]          = KeyCode2,
    [ScanCode3]          = KeyCode3,
    [ScanCode4]          = KeyCode4,
    [ScanCode5]          = KeyCode5,
    [ScanCode6]          = KeyCode6,
    [ScanCode7]          = KeyCode7,
    [ScanCode8]          = KeyCode8,
    [ScanCode9]          = KeyCode9,
    [ScanCode0]          = KeyCode0,
    [ScanCodeMinus]      = KeyCodeMinus,
    [ScanCodeEquals]     = KeyCodeEquals,
    [ScanCodeBackspace]  = KeyCodeBackspace,
    [ScanCodeTab]        = KeyCodeTab,
    [ScanCodeQ]          = KeyCodeQ,
    [ScanCodeW]          = KeyCodeW,
    [ScanCodeE]          = KeyCodeE,
    [ScanCodeR]          = KeyCodeR,
    [ScanCodeT]          = KeyCodeT,
    [ScanCodeY]          = KeyCodeZ,
    [ScanCodeU]          = KeyCodeU,
    [ScanCodeI]          = KeyCodeI,
    [ScanCodeO]          = KeyCodeO,
    [ScanCodeP]          = KeyCodeP,
    [ScanCodeEnter]      = KeyCodeEnter,
    [ScanCodeLCtrl]      = KeyCodeLCtrl,
    [ScanCodeA]          = KeyCodeA,
    [ScanCodeS]          = KeyCodeS,
    [ScanCodeD]          = KeyCodeD,
    [ScanCodeF]          = KeyCodeF,
    [ScanCodeG]          = KeyCodeG,
    [ScanCodeH]          = KeyCodeH,
    [ScanCodeJ]          = KeyCodeJ,
    [ScanCodeK]          = KeyCodeK,
    [ScanCodeL]          = KeyCodeL,
    [ScanCodeLShift]     = KeyCodeLShift,
    [ScanCodeZ]          = KeyCodeY,
    [ScanCodeX]          = KeyCodeX,
    [ScanCodeC]          = KeyCodeC,
    [ScanCodeV]          = KeyCodeV,
    [ScanCodeB]          = KeyCodeB,
    [ScanCodeN]          = KeyCodeN,
    [ScanCodeM]          = KeyCodeM,
    [ScanCodeComma]      = KeyCodeComma,
    [ScanCodePeriod]     = KeyCodePeriod,
    [ScanCodeSlash]      = KeyCodeMinus,
    [ScanCodeRShift]     = KeyCodeRShift,
    [ScanCodeKpAsterisk] = KeyCodeKpAsterisk,
    [ScanCodeLAlt]       = KeyCodeLAlt,
    [ScanCodeSpace]      = KeyCodeSpace,
    [ScanCodeCapsLock]   = KeyCodeCapsLock,
    [ScanCodeF1]         = KeyCodeF1,
    [ScanCodeF2]         = KeyCodeF2,
    [ScanCodeF3]         = KeyCodeF3,
    [ScanCodeF4]         = KeyCodeF4,
    [ScanCodeF5]         = KeyCodeF5,
    [ScanCodeF6]         = KeyCodeF6,
    [ScanCodeF7]         = KeyCodeF7,
    [ScanCodeF8]         = KeyCodeF8,
    [ScanCodeF9]         = KeyCodeF9,
    [ScanCodeF10]        = KeyCodeF10,
    [ScanCodeNumLock]    = KeyCodeNumLock,
    [ScanCodeScrollLock] = KeyCodeScrollLock,
    [ScanCodeKp7]        = KeyCodeKp7,
    [ScanCodeKp8]        = KeyCodeKp8,
    [ScanCodeKp9]        = KeyCodeKp9,
    [ScanCodeKpMinus]    = KeyCodeKpMinus,
    [ScanCodeKp4]        = KeyCodeKp4,
    [ScanCodeKp5]        = KeyCodeKp5,
    [ScanCodeKp6]        = KeyCodeKp6,
    [ScanCodeKpPlus]     = KeyCodeKpPlus,
    [ScanCodeKp1]        = KeyCodeKp1,
    [ScanCodeKp2]        = KeyCodeKp2,
    [ScanCodeKp3]        = KeyCodeKp3,
    [ScanCodeKp0]        = KeyCodeKp0,
    [ScanCodeKpPeriod]   = KeyCodeKpPeriod,
    [ScanCodeF11]        = KeyCodeF11,
    [ScanCodeF12]        = KeyCodeF12
    };

static const char GermanCharSet[0xff][3] = {
  [KeyCodeNone] = {0,0,0},
  [KeyCodeError] = {0,0,0},
  [KeyCodeReserved]= {0,0,0},
  [KeyCodeSystem]= {0,0,0},

[KeyCodeA] = {'a', 'A', 0},
[KeyCodeB] = {'b', 'B', 0},
[KeyCodeC] = {'c', 'C', 0},
[KeyCodeD] = {'d', 'D', 0},
[KeyCodeE] = {'e', 'E', 0},
[KeyCodeF] = {'f', 'F', 0},
[KeyCodeG] = {'g', 'G', 0},
[KeyCodeH] = {'h', 'H', 0},
[KeyCodeI] = {'i', 'A', 0},
[KeyCodeJ] = {'j', 'B', 0},
[KeyCodeK] = {'k', 'C', 0},
[KeyCodeL] = {'l', 'D', 0},
[KeyCodeM] = {'m', 'E', 0},
[KeyCodeN] = {'n', 'F', 0},
[KeyCodeO] = {'o', 'G', 0},
[KeyCodeP] = {'p', 'H', 0},
[KeyCodeQ] = {'q', 'A', 0},
[KeyCodeR] = {'r', 'B', 0},
[KeyCodeS] = {'s', 'C', 0},
[KeyCodeT] = {'t', 'D', 0},
[KeyCodeU] = {'u', 'E', 0},
[KeyCodeV] = {'v', 'F', 0},
[KeyCodeW] = {'w', 'G', 0},
[KeyCodeX] = {'x', 'H', 0},
[KeyCodeY] = {'y', 'A', 0},
[KeyCodeZ] = {'z', 'B', 0},

[KeyCodeC] = {'c', 'C', 0},
[KeyCodeD] = {'d', 'D', 0},
[KeyCodeE] = {'e', 'E', 0},
[KeyCodeF] = {'f', 'F', 0},
[KeyCodeG] = {'g', 'G', 0},
[KeyCodeH] = {'h', 'H', 0},

    [KeyCodeSpace]     = { ' ', ' ', '_' },

    [KeyCode1]         = { '1', '!', '_' },
    [KeyCode2]         = { '2', '"', '_' },
    [KeyCode3]         = { '3', '_', '_' },
    [KeyCode4]         = { '4', '$', '_' },
    [KeyCode5]         = { '5', '%', '_' },
    [KeyCode6]         = { '6', '&', '_' },
    [KeyCode7]         = { '7', '/', '{' },
    [KeyCode8]         = { '8', '(', '[' },
    [KeyCode9]         = { '9', ')', ']' },
    [KeyCode0]         = { '0', '=', '}' },
    [KeyCodeMinus]     = { '_', '?', '\\' },
    [KeyCodeEquals]    = { '_', '`', '_' },

    [KeyCodeQ]         = { 'q', 'Q', '@' },
    [KeyCodeW]         = { 'w', 'W', '_' },
    [KeyCodeE]         = { 'e', 'E', '_' },
    [KeyCodeR]         = { 'r', 'R', '_' },
    [KeyCodeT]         = { 't', 'T', '_' },
    [KeyCodeZ]         = { 'z', 'Z', '_' },
    [KeyCodeU]         = { 'u', 'U', '_' },
    [KeyCodeI]         = { 'i', 'I', '_' },
    [KeyCodeO]         = { 'o', 'O', '_' },
    [KeyCodeP]         = { 'p', 'P', '_' },

    [KeyCodeA]         = { 'a', 'A', '_' },
    [KeyCodeS]         = { 's', 'S', '_' },
    [KeyCodeD]         = { 'd', 'D', '_' },
    [KeyCodeF]         = { 'f', 'F', '_' },
    [KeyCodeG]         = { 'g', 'G', '_' },
    [KeyCodeH]         = { 'h', 'H', '_' },
    [KeyCodeJ]         = { 'j', 'J', '_' },
    [KeyCodeK]         = { 'k', 'K', '_' },
    [KeyCodeL]         = { 'l', 'L', '_' },

    [KeyCodeY]         = { 'y', 'Y', '_' },
    [KeyCodeX]         = { 'x', 'X', '_' },
    [KeyCodeC]         = { 'c', 'C', '_' },
    [KeyCodeV]         = { 'v', 'V', '_' },
    [KeyCodeB]         = { 'b', 'B', '_' },
    [KeyCodeN]         = { 'n', 'N', '_' },
    [KeyCodeM]         = { 'm', 'M', '_' },
    [KeyCodeComma]     = { ',', ';', '_' },
    [KeyCodePeriod]    = { '.', ':', '_' }
  };



#endif
