name: Build Floppies

on:
  push:
    branches:
      - main

jobs:
  build-toolchain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y make bison flex mtools libgmp3-dev libmpc-dev libmpfr-dev texinfo libisoburn-dev

      - name: Build Toolchain
        working-directory: Tools
        run: make
        
      - name: Create ZIP Archive
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          zip -r "i386-toolchain-bin.${YEAR}.${MONTH}.zip" . -x Makefile *.mk check-deps.archlinux.sh
        working-directory: Tools

      - name: Upload Toolchain Archive
        uses: actions/upload-artifact@v4
        with:
          name: i386-toolchain
          path: Tools/i386-toolchain-bin.*.zip

      - name: Build Floppy Image
        working-directory: Source
        run: make floppy

      - name: Upload Floppy Image
        uses: actions/upload-artifact@v4
        with:
          name: free86-floppies
          path: Build/Kickstart.img
        
          
